//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Console.Monitoring {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Monitoring.IMonitoringService")]
    public interface IMonitoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNbRqtToJCDCo", ReplyAction="http://tempuri.org/IMonitoringService/GetNbRqtToJCDCoResponse")]
        int GetNbRqtToJCDCo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNbRqtToJCDCo", ReplyAction="http://tempuri.org/IMonitoringService/GetNbRqtToJCDCoResponse")]
        System.Threading.Tasks.Task<int> GetNbRqtToJCDCoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNbRqtFromCache", ReplyAction="http://tempuri.org/IMonitoringService/GetNbRqtFromCacheResponse")]
        int GetNbRqtFromCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetNbRqtFromCache", ReplyAction="http://tempuri.org/IMonitoringService/GetNbRqtFromCacheResponse")]
        System.Threading.Tasks.Task<int> GetNbRqtFromCacheAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetTotalRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetTotalRqtResponse")]
        int GetTotalRqt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetTotalRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetTotalRqtResponse")]
        System.Threading.Tasks.Task<int> GetTotalRqtAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetAverageTimePerRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetAverageTimePerRqtResponse")]
        long GetAverageTimePerRqt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetAverageTimePerRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetAverageTimePerRqtResponse")]
        System.Threading.Tasks.Task<long> GetAverageTimePerRqtAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetDateLastRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetDateLastRqtResponse")]
        string GetDateLastRqt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitoringService/GetDateLastRqt", ReplyAction="http://tempuri.org/IMonitoringService/GetDateLastRqtResponse")]
        System.Threading.Tasks.Task<string> GetDateLastRqtAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitoringServiceChannel : Client_Console.Monitoring.IMonitoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitoringServiceClient : System.ServiceModel.ClientBase<Client_Console.Monitoring.IMonitoringService>, Client_Console.Monitoring.IMonitoringService {
        
        public MonitoringServiceClient() {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetNbRqtToJCDCo() {
            return base.Channel.GetNbRqtToJCDCo();
        }
        
        public System.Threading.Tasks.Task<int> GetNbRqtToJCDCoAsync() {
            return base.Channel.GetNbRqtToJCDCoAsync();
        }
        
        public int GetNbRqtFromCache() {
            return base.Channel.GetNbRqtFromCache();
        }
        
        public System.Threading.Tasks.Task<int> GetNbRqtFromCacheAsync() {
            return base.Channel.GetNbRqtFromCacheAsync();
        }
        
        public int GetTotalRqt() {
            return base.Channel.GetTotalRqt();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalRqtAsync() {
            return base.Channel.GetTotalRqtAsync();
        }
        
        public long GetAverageTimePerRqt() {
            return base.Channel.GetAverageTimePerRqt();
        }
        
        public System.Threading.Tasks.Task<long> GetAverageTimePerRqtAsync() {
            return base.Channel.GetAverageTimePerRqtAsync();
        }
        
        public string GetDateLastRqt() {
            return base.Channel.GetDateLastRqt();
        }
        
        public System.Threading.Tasks.Task<string> GetDateLastRqtAsync() {
            return base.Channel.GetDateLastRqtAsync();
        }
    }
}
