//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Console.VelibSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibSOAP.IIntermediaryService")]
    public interface IIntermediaryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStations", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationsResponse")]
        string GetStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStations", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationsResponse")]
        System.Threading.Tasks.Task<string> GetStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStationsCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationsCityResponse")]
        string GetStationsCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStationsCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationsCityResponse")]
        System.Threading.Tasks.Task<string> GetStationsCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStation", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationResponse")]
        string GetStation(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetStation", ReplyAction="http://tempuri.org/IIntermediaryService/GetStationResponse")]
        System.Threading.Tasks.Task<string> GetStationAsync(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetNbBikes", ReplyAction="http://tempuri.org/IIntermediaryService/GetNbBikesResponse")]
        string GetNbBikes(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetNbBikes", ReplyAction="http://tempuri.org/IIntermediaryService/GetNbBikesResponse")]
        System.Threading.Tasks.Task<string> GetNbBikesAsync(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetNbBikesCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetNbBikesCityResponse")]
        string GetNbBikesCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetNbBikesCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetNbBikesCityResponse")]
        System.Threading.Tasks.Task<string> GetNbBikesCityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetPosition", ReplyAction="http://tempuri.org/IIntermediaryService/GetPositionResponse")]
        string GetPosition(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetPosition", ReplyAction="http://tempuri.org/IIntermediaryService/GetPositionResponse")]
        System.Threading.Tasks.Task<string> GetPositionAsync(string idStation, string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetPositions", ReplyAction="http://tempuri.org/IIntermediaryService/GetPositionsResponse")]
        string GetPositions(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetPositions", ReplyAction="http://tempuri.org/IIntermediaryService/GetPositionsResponse")]
        System.Threading.Tasks.Task<string> GetPositionsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetCities", ReplyAction="http://tempuri.org/IIntermediaryService/GetCitiesResponse")]
        string GetCities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetCities", ReplyAction="http://tempuri.org/IIntermediaryService/GetCitiesResponse")]
        System.Threading.Tasks.Task<string> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetCityResponse")]
        string GetCity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntermediaryService/GetCity", ReplyAction="http://tempuri.org/IIntermediaryService/GetCityResponse")]
        System.Threading.Tasks.Task<string> GetCityAsync(string city);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntermediaryServiceChannel : Client_Console.VelibSOAP.IIntermediaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntermediaryServiceClient : System.ServiceModel.ClientBase<Client_Console.VelibSOAP.IIntermediaryService>, Client_Console.VelibSOAP.IIntermediaryService {
        
        public IntermediaryServiceClient() {
        }
        
        public IntermediaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntermediaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntermediaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStations() {
            return base.Channel.GetStations();
        }
        
        public System.Threading.Tasks.Task<string> GetStationsAsync() {
            return base.Channel.GetStationsAsync();
        }
        
        public string GetStationsCity(string city) {
            return base.Channel.GetStationsCity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsCityAsync(string city) {
            return base.Channel.GetStationsCityAsync(city);
        }
        
        public string GetStation(string idStation, string city) {
            return base.Channel.GetStation(idStation, city);
        }
        
        public System.Threading.Tasks.Task<string> GetStationAsync(string idStation, string city) {
            return base.Channel.GetStationAsync(idStation, city);
        }
        
        public string GetNbBikes(string idStation, string city) {
            return base.Channel.GetNbBikes(idStation, city);
        }
        
        public System.Threading.Tasks.Task<string> GetNbBikesAsync(string idStation, string city) {
            return base.Channel.GetNbBikesAsync(idStation, city);
        }
        
        public string GetNbBikesCity(string city) {
            return base.Channel.GetNbBikesCity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetNbBikesCityAsync(string city) {
            return base.Channel.GetNbBikesCityAsync(city);
        }
        
        public string GetPosition(string idStation, string city) {
            return base.Channel.GetPosition(idStation, city);
        }
        
        public System.Threading.Tasks.Task<string> GetPositionAsync(string idStation, string city) {
            return base.Channel.GetPositionAsync(idStation, city);
        }
        
        public string GetPositions(string city) {
            return base.Channel.GetPositions(city);
        }
        
        public System.Threading.Tasks.Task<string> GetPositionsAsync(string city) {
            return base.Channel.GetPositionsAsync(city);
        }
        
        public string GetCities() {
            return base.Channel.GetCities();
        }
        
        public System.Threading.Tasks.Task<string> GetCitiesAsync() {
            return base.Channel.GetCitiesAsync();
        }
        
        public string GetCity(string city) {
            return base.Channel.GetCity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetCityAsync(string city) {
            return base.Channel.GetCityAsync(city);
        }
    }
}
